spring.application.name=topic selector
server.port=8080
####################hacker-news#######################
hackernews.topstories.url=https://hacker-news.firebaseio.com/v0/topstories.json
hackernews.storydetail.url=https://hacker-news.firebaseio.com/v0/item/{id}.json